baseURL = "/"
languageCode = "en-us"
title = "Byte Geek"
theme="hermit"
enableEmoji=true
googleAnalytics = "UA-200805095-1"
[taxonomies]
  tag = "tags"

[author]
	name = "thewildofficial"
[params]
	
	dateform        = "Jan 2, 2006"
  	dateformShort   = "Jan 2"
  	dateformNum     = "2006-01-02"
  	dateformNumTime = "2006-01-02 15:04 -0700"
	relatedPosts=true
	themeColor = "#181a1b"
	code_copy_button = true
	description = "Hi I'm Aban. Im 15 and  love learning. In my extremely succinct blog posts I explore novel and arbritary concepts in a fun way!"
	#customCSS = ["css/foo.css"]



	homeSubtitle="always learning."
	[[params.social]]
		name="github"
		url = "https://github.com/thewildofficial"
	[[params.social]]
		name="youtube"
		url = "https://www.youtube.com/channel/UCgmwvznKWmu-bAEtIbTT05w"
	[[params.social]]
		name="twitter"
		url="https://twitter.com/0xwild"



[menu]
	[[menu.main]]
    	name = "Posts"
    	url = "/posts/"
    	weight = 10
	#[[menu.main]]
	#	 name = "About"
	#	 url = "/about"
	#	 weight = 10










# SEO TITLE : Byte Geek: Short Reads About Productivity And Technology
