baseURL = "/"
languageCode = "en-us"
title = "Byte Geek"
theme="hermit"
enableEmoji=true

[author]
	name = "thewildofficial"
[params]
	dateform        = "Jan 2, 2006"
  	dateformShort   = "Jan 2"
  	dateformNum     = "2006-01-02"
  	dateformNumTime = "2006-01-02 15:04 -0700"
	relatedPosts=true
	homeSubtitle="always learning."
	[[params.social]]
		name="github"
		url = "https://github.com/thewildofficial"



[menu]
	[[menu.main]]
    	name = "Posts"
    	url = "/posts/"
    	weight = 10
	#[[menu.main]]
	#	 name = "About"
	#	 url = "/about"
	#	 weight = 10
